### ISSUE TITLE
Feedback meal-sharing

### ISSUE THREAD

**Issue by OlkaA** [MirSzabo/meal-sharing-website#1]
Great job! Very good looking and impressive website. 👍
Good that you are using variables in css.

Small suggestions: 
- try to keep your code without console.log. (inside folder api)
- `  const { maxPrice } = req.query;
  const { availableReservations } = req.query;
  const { title } = req.query;
  const { createdAfter } = req.query;
  const { limit } = req.query;`
you can write as object destructuring 
` const { maxPrice , availableReservations, title, createdAfter, limit } = req.query`
- probably it is better to keep all styles for the specific width in one place
@media only screen and (max-width: 56.25em) { }

**Comment by MirSzabo** [comment]
Hi Olha, great that you are helping with reviews! and such a difficult topic :O thanks :)
- console.log deleted
- changed
- yes this is I think matter of taste, it would be less lines but more scrolling :)
